[package]
name = "any-fn"
description = "Dynamically-typed functions to represent any functions in Rust"
version = "0.1.3"
edition = "2021"
license-file = "./LICENSE"
repository = "https://github.com/raviqqe/any-fn"

[dependencies]

[lints.rust]
missing_docs = "deny"
warnings = "deny"
