[package]
name = "any-fn"
description = "Data structure to represent any functions"
version = "0.1.0"
edition = "2021"
license-file = "./LICENSE"
repository = "https://github.com/raviqqe/any-fn"

[dependencies]

[lints.rust]
missing_docs = "deny"
warnings = "deny"
