[package]
name = "any-fn"
version = "0.6.2"
edition = "2024"
description = "Dynamically-typed functions to represent any functions in Rust"
repository = "https://github.com/raviqqe/any-fn"
license-file = "./LICENSE"

[dependencies]

[lints.rust]
missing_docs = "deny"
warnings = "deny"
